services:
  app:
    build:
      context: ./fiap-bytebank-backend
    container_name: bytebank_backend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/bytebank
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    container_name: bytebank_mongo_novo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  frontend:
    build:
      context: ./sistema-financeiro  # Caminho para o diretório do seu front-end
    container_name: bytebank_frontend
    ports:
      - '3001:3000'  # Mapeia a porta 3000 do contêiner para 3001 na máquina local
    depends_on:
      - app  # Garante que o back-end esteja rodando antes de iniciar o front-end
    environment:
      - REACT_APP_API_URL=http://app:3000  # URL da API do back-end no Docker Compose
    volumes:
      - ./sistema-financeiro:/usr/src/app  # Monta o diretório do front-end no contêiner para desenvolvimento em tempo real

volumes:
  mongo-data: